const PLAYJOIN_STORAGE_KEYS = {
  users: "playjoin_users",
  session: "playjoin_session",
  matches: "playjoin_matches",
  theme: "playjoin_theme",
  language: "playjoin_language",
  location: "playjoin_location"
};

const PLAYJOIN_LOCATIONS = [
  "Istanbul",
  "Ankara",
  "Izmir",
  "Baghdad",
  "Basra",
  "Erbil",
  "Berlin",
  "Munich"
];

const PLAYJOIN_MATCH_TYPES = ["5v5", "6v6", "7v7", "8v8", "11v11", "Friendly", "Competitive"];

const PLAYJOIN_DEFAULT_MATCHES = [
  {
    id: "match-1",
    teamName: "Team Falcons",
    fieldName: "Florya Arena",
    location: "Istanbul",
    date: "2026-04-01",
    time: "20:00",
    matchType: "7v7",
    notes: "Booked under floodlights. Looking for energetic midfielders and one defender.",
    totalNeeded: 2,
    joinedPlayers: 0,
    createdByUser: false,
    joinedByUser: false
  },
  {
    id: "match-2",
    teamName: "Basra Stars",
    fieldName: "Basra Sport Center",
    location: "Basra",
    date: "2026-04-02",
    time: "18:00",
    matchType: "5v5",
    notes: "Fast-paced small pitch game. Bring dark shirts if possible.",
    totalNeeded: 1,
    joinedPlayers: 0,
    createdByUser: false,
    joinedByUser: false
  },
  {
    id: "match-3",
    teamName: "Baghdad Lions",
    fieldName: "Green Field",
    location: "Baghdad",
    date: "2026-04-03",
    time: "21:00",
    matchType: "8v8",
    notes: "Competitive community night. Need players who can keep shape.",
    totalNeeded: 3,
    joinedPlayers: 1,
    createdByUser: false,
    joinedByUser: false
  },
  {
    id: "match-4",
    teamName: "Ankara United",
    fieldName: "Goal Arena",
    location: "Ankara",
    date: "2026-04-04",
    time: "19:00",
    matchType: "6v6",
    notes: "Balanced match for mixed skill levels. Arrive 20 minutes early.",
    totalNeeded: 2,
    joinedPlayers: 0,
    createdByUser: false,
    joinedByUser: false
  },
  {
    id: "match-5",
    teamName: "Erbil Eagles",
    fieldName: "Dream Field",
    location: "Erbil",
    date: "2026-04-01",
    time: "22:00",
    matchType: "5v5",
    notes: "Late night kickoff. One attacker needed immediately.",
    totalNeeded: 1,
    joinedPlayers: 0,
    createdByUser: false,
    joinedByUser: false
  },
  {
    id: "match-6",
    teamName: "Berlin Kickers",
    fieldName: "Arena Park",
    location: "Berlin",
    date: "2026-04-05",
    time: "17:00",
    matchType: "7v7",
    notes: "Weekend social game with rotating positions and quick breaks.",
    totalNeeded: 2,
    joinedPlayers: 0,
    createdByUser: false,
    joinedByUser: false
  },
  {
    id: "match-7",
    teamName: "Izmir Wave",
    fieldName: "Coastline Turf",
    location: "Izmir",
    date: "2026-04-06",
    time: "20:30",
    matchType: "Friendly",
    notes: "Friendly game near the coast. Ideal for casual players.",
    totalNeeded: 4,
    joinedPlayers: 2,
    createdByUser: false,
    joinedByUser: false
  },
  {
    id: "match-8",
    teamName: "Munich Strikers",
    fieldName: "Olympia Cage",
    location: "Munich",
    date: "2026-04-02",
    time: "19:30",
    matchType: "Competitive",
    notes: "High-tempo game. Need players who can press and recover quickly.",
    totalNeeded: 2,
    joinedPlayers: 1,
    createdByUser: false,
    joinedByUser: false
  },
  {
    id: "match-9",
    teamName: "Golden Boots",
    fieldName: "North Goal Hub",
    location: "Istanbul",
    date: "2026-04-07",
    time: "18:30",
    matchType: "11v11",
    notes: "Full pitch training match. Need flexible wide players.",
    totalNeeded: 3,
    joinedPlayers: 1,
    createdByUser: false,
    joinedByUser: false
  },
  {
    id: "match-10",
    teamName: "Capital Press",
    fieldName: "Victory Turf",
    location: "Berlin",
    date: "2026-04-01",
    time: "21:15",
    matchType: "6v6",
    notes: "Need one final player for tonight's pressing game.",
    totalNeeded: 1,
    joinedPlayers: 0,
    createdByUser: false,
    joinedByUser: false
  }
];

const PLAYJOIN_TRANSLATIONS = {
  en: {
    brandTag: "Football Team-Up Platform",
    navHome: "Dashboard",
    navActivity: "My Activity",
    navSettings: "Settings",
    loginTitle: "Welcome Back",
    loginSubtitle: "Log in and jump into tonight's football action.",
    signupTitle: "Create Your Squad Profile",
    signupSubtitle: "Join the football community and start matching with teams.",
    fullName: "Full Name",
    email: "Email Address",
    password: "Password",
    confirmPassword: "Confirm Password",
    login: "Log In",
    signup: "Create Account",
    noAccount: "Need an account?",
    haveAccount: "Already registered?",
    createAccount: "Create account",
    backToLogin: "Back to login",
    heroTitle: "Need players? Find a football match in minutes.",
    heroText: "Connect teams missing players with footballers ready to join today, tomorrow, or matchday weekend.",
    heroPrimary: "Create Match Request",
    heroSecondary: "Browse Open Matches",
    liveMatches: "Live Open Matches",
    playersNeeded: "Players Needed",
    todaysKickoffs: "Today's Kickoffs",
    joinedCount: "Joined By You",
    quickActions: "Quick Actions",
    createRequest: "Create Request",
    viewActivity: "View Activity",
    openFilters: "Match Filters",
    searchPlaceholder: "Search by team or field...",
    locationFilter: "Location",
    typeFilter: "Match Type",
    allLocations: "All Locations",
    allTypes: "All Types",
    resetFilters: "Reset Filters",
    openMatches: "Open Matches",
    urgentMatches: "Urgent Match Calls",
    needOnePlayer: "Need 1 Player",
    needTwoPlayers: "Need 2+ Players",
    today: "Today",
    open: "Open",
    full: "Full",
    remainingSlots: "Remaining Slots",
    joinedPlayersLabel: "Joined Players",
    totalNeeded: "Total Needed",
    details: "Details",
    noMatches: "No matches found for the current filters.",
    createTitle: "Publish Missing Players Request",
    teamName: "Team Name",
    fieldName: "Field Name",
    city: "City / Location",
    date: "Date",
    time: "Time",
    missingPlayers: "Missing Players",
    notes: "Notes",
    submitRequest: "Publish Request",
    activityTitle: "Your Football Activity Center",
    myRequests: "My Created Requests",
    joinedMatches: "Joined Matches",
    emptyCreated: "You have not created any match requests yet.",
    emptyJoined: "You have not joined any matches yet.",
    detailsTitle: "Match Details",
    joinMatch: "Join Match",
    alreadyJoined: "Already Joined",
    matchStatus: "Match Status",
    profileTitle: "Player Profile",
    memberSubtitle: "Football Player / Community Member",
    themeMode: "Theme Mode",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    language: "Language",
    locationPreference: "Location Preference",
    logout: "Log Out",
    backDashboard: "Back to Dashboard",
    savePreferences: "Preferences are saved automatically.",
    english: "English",
    turkish: "Turkish",
    german: "German"
  },
  tr: {
    brandTag: "Futbol Takim Eslestirme Platformu",
    navHome: "Panel",
    navActivity: "Aktivitem",
    navSettings: "Ayarlar",
    loginTitle: "Tekrar Hos Geldin",
    loginSubtitle: "Giris yap ve bu aksamki futbol aksiyonuna katil.",
    signupTitle: "Oyuncu Profili Olustur",
    signupSubtitle: "Futbol topluluguna katil ve takimlarla eslesmeye basla.",
    fullName: "Ad Soyad",
    email: "E-posta",
    password: "Sifre",
    confirmPassword: "Sifreyi Onayla",
    login: "Giris Yap",
    signup: "Hesap Olustur",
    noAccount: "Hesabin yok mu?",
    haveAccount: "Zaten kayitli misin?",
    createAccount: "Hesap olustur",
    backToLogin: "Girise don",
    heroTitle: "Oyuncu mu lazim? Dakikalar icinde mac bul.",
    heroText: "Eksik oyuncusu olan takimlari bugun, yarin veya hafta sonu maca hazir oyuncularla bulustur.",
    heroPrimary: "Mac Ilani Olustur",
    heroSecondary: "Acik Maclari Gor",
    liveMatches: "Acik Maclar",
    playersNeeded: "Gerekli Oyuncular",
    todaysKickoffs: "Bugunun Maclari",
    joinedCount: "Katildiklarin",
    quickActions: "Hizli Islemler",
    createRequest: "Ilan Olustur",
    viewActivity: "Aktiviteyi Gor",
    openFilters: "Mac Filtreleri",
    searchPlaceholder: "Takim veya saha ara...",
    locationFilter: "Konum",
    typeFilter: "Mac Turu",
    allLocations: "Tum Konumlar",
    allTypes: "Tum Turler",
    resetFilters: "Filtreleri Temizle",
    openMatches: "Acik Maclar",
    urgentMatches: "Acil Oyuncu Arayanlar",
    needOnePlayer: "1 Oyuncu Lazim",
    needTwoPlayers: "2+ Oyuncu Lazim",
    today: "Bugun",
    open: "Acik",
    full: "Dolu",
    remainingSlots: "Kalan Yer",
    joinedPlayersLabel: "Katilan Oyuncular",
    totalNeeded: "Toplam Ihtiyac",
    details: "Detaylar",
    noMatches: "Mevcut filtrelere uygun mac bulunamadi.",
    createTitle: "Eksik Oyuncu Ilani Yayinla",
    teamName: "Takim Adi",
    fieldName: "Saha Adi",
    city: "Sehir / Konum",
    date: "Tarih",
    time: "Saat",
    missingPlayers: "Eksik Oyuncu Sayisi",
    notes: "Notlar",
    submitRequest: "Ilani Yayinla",
    activityTitle: "Futbol Aktivite Merkezi",
    myRequests: "Olusturdugum Ilanlar",
    joinedMatches: "Katildigim Maclar",
    emptyCreated: "Henuz bir mac ilani olusturmadin.",
    emptyJoined: "Henuz hicbir maca katilmadin.",
    detailsTitle: "Mac Detaylari",
    joinMatch: "Maca Katil",
    alreadyJoined: "Zaten Katildin",
    matchStatus: "Mac Durumu",
    profileTitle: "Oyuncu Profili",
    memberSubtitle: "Futbol Oyuncusu / Topluluk Uyesi",
    themeMode: "Tema Modu",
    lightMode: "Aydinlik Mod",
    darkMode: "Karanlik Mod",
    language: "Dil",
    locationPreference: "Konum Tercihi",
    logout: "Cikis Yap",
    backDashboard: "Panele Don",
    savePreferences: "Tercihler otomatik olarak kaydedilir.",
    english: "Ingilizce",
    turkish: "Turkce",
    german: "Almanca"
  },
  de: {
    brandTag: "Fussball Team-Up Plattform",
    navHome: "Dashboard",
    navActivity: "Meine Aktivitaet",
    navSettings: "Einstellungen",
    loginTitle: "Willkommen zurueck",
    loginSubtitle: "Melde dich an und werde Teil des heutigen Fussballabends.",
    signupTitle: "Erstelle dein Spielerprofil",
    signupSubtitle: "Tritt der Fussball-Community bei und finde passende Teams.",
    fullName: "Vollstaendiger Name",
    email: "E-Mail",
    password: "Passwort",
    confirmPassword: "Passwort bestaetigen",
    login: "Einloggen",
    signup: "Konto erstellen",
    noAccount: "Noch kein Konto?",
    haveAccount: "Bereits registriert?",
    createAccount: "Konto erstellen",
    backToLogin: "Zurueck zum Login",
    heroTitle: "Spieler gesucht? Finde schnell dein Fussballspiel.",
    heroText: "Verbinde Teams mit fehlenden Spielern und Fussballer, die sofort einspringen koennen.",
    heroPrimary: "Anfrage erstellen",
    heroSecondary: "Offene Spiele ansehen",
    liveMatches: "Offene Spiele",
    playersNeeded: "Gesuchte Spieler",
    todaysKickoffs: "Heutige Anstosse",
    joinedCount: "Von dir beigetreten",
    quickActions: "Schnellaktionen",
    createRequest: "Anfrage erstellen",
    viewActivity: "Aktivitaet ansehen",
    openFilters: "Spiel Filter",
    searchPlaceholder: "Nach Team oder Platz suchen...",
    locationFilter: "Ort",
    typeFilter: "Spieltyp",
    allLocations: "Alle Orte",
    allTypes: "Alle Typen",
    resetFilters: "Filter zuruecksetzen",
    openMatches: "Offene Spiele",
    urgentMatches: "Dringende Spielaufrufe",
    needOnePlayer: "1 Spieler gesucht",
    needTwoPlayers: "2+ Spieler gesucht",
    today: "Heute",
    open: "Offen",
    full: "Voll",
    remainingSlots: "Verbleibende Plaetze",
    joinedPlayersLabel: "Beigetretene Spieler",
    totalNeeded: "Gesamtbedarf",
    details: "Details",
    noMatches: "Keine Spiele fuer die aktuellen Filter gefunden.",
    createTitle: "Anfrage fuer fehlende Spieler",
    teamName: "Teamname",
    fieldName: "Platzname",
    city: "Stadt / Ort",
    date: "Datum",
    time: "Uhrzeit",
    missingPlayers: "Fehlende Spieler",
    notes: "Notizen",
    submitRequest: "Anfrage veroeffentlichen",
    activityTitle: "Dein Fussball Aktivitaetscenter",
    myRequests: "Meine erstellten Anfragen",
    joinedMatches: "Beigetretene Spiele",
    emptyCreated: "Du hast noch keine Spielanfragen erstellt.",
    emptyJoined: "Du bist noch keinem Spiel beigetreten.",
    detailsTitle: "Spieldetails",
    joinMatch: "Spiel beitreten",
    alreadyJoined: "Bereits beigetreten",
    matchStatus: "Spielstatus",
    profileTitle: "Spielerprofil",
    memberSubtitle: "Fussballspieler / Community Mitglied",
    themeMode: "Themenmodus",
    lightMode: "Heller Modus",
    darkMode: "Dunkler Modus",
    language: "Sprache",
    locationPreference: "Bevorzugter Ort",
    logout: "Abmelden",
    backDashboard: "Zurueck zum Dashboard",
    savePreferences: "Einstellungen werden automatisch gespeichert.",
    english: "Englisch",
    turkish: "Tuerkisch",
    german: "Deutsch"
  }
};
